Deltares/xugrid

docs/_templates/navbar.html
The `get_nav_object()` function was removed in the PyData Sphinx theme version 7.0.
This fix uses the newer more generic `generate_nav_html()` to do the same.
=> Update navbar to not use a function removed from the PyData Sphinx Theme.

xugrid/ugrid/snapping.py
Fix typehints causing ImportError for the optional dependency geopandas.
Closes #77
=> Avoid geopandas ImporError when hitting typehints

tests/test_conversion.py
[A test is failing](https://github.com/Deltares/xugrid/actions/runs/5938758920/job/16103843774) due to the most recent xarray v2023.08.0 update. Apparently the indexes attribute is not updated anymore when setting values on coordinates as follows:
```python
up = xr.DataArray(
data=np.arange(4),
coords={"x": [2.0, 4.0, 6.0, 8.0]},
dims=["x"],
name="grid",
)
up["x"].values[2] = 3.0
print(up["x"].indexes)
```
But this works:
```python
up = up.assign_coords(x = [2.0, 4.0, 3.0, 8.0])
print(up["x"].indexes)
```
[It turns out the first example is not what the xarray devs have in mind on how coords should be set](https://github.com/pydata/xarray/issues/7463#issuecomment-1428391853), so this explains why this test is failing without this fix.
=> Fix arrangement of test_infer_bounds_errors after xarray v2023.08.0

xugrid/plot/plot.py
`import_matplotlib_pyplot` and the follow-up `plt = import_matplotlib_pyplot()` was not used in this script
=> removed `import_matplotlib_pyplot` to support xarray 2023.9.0

docs/changelog.rst, tests/test_ugrid1d.py, tests/test_ugrid2d.py, xugrid/core/utils.py, xugrid/ugrid/ugridbase.py
Fixes: https://github.com/Deltares/xugrid/issues/206, related to: https://github.com/Deltares/xugrid/issues/205
Unfortunately, I accidently pushed my changes to ``main``.
@Huite reviewed the changes via chat. This PR is to deal with these review comments.
PR implements the following:
- ``__eq__`` can be removed, as it is not equivalent to the pandas behavior
- ``.identical`` can be renamed to ``.equals`` and original ``.equals`` can be removed
- If else structure is reordered in ``.equals``, to make it more comprehensible
- ``to_xr_if_possible()`` is removed as it was unnecessary
=> Fix #206. Deal with review comments

tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/ugrid/ugridbase.py
@Huite [your suggestion](https://github.com/Deltares/xugrid/issues/208#issuecomment-1921615348) works and I have implemented it in this PR including a testcase that failed before the `.copy()` was added. I guess this is therefore a valid fix. However, I also noticed it works when calling `ds = xr.decode_cf(ds)` upon trying to create a testcase for this situation. This is unexpected, since `ds = xr.open_dataset(file_nc)` also has a `decode_cf=True` as default. Maybe this triggers you to find a solution elsewhere in the code. If not, I think this PR can be merged.
=> add test to wrap ugriddataset twice (should fail now)

pyproject.toml, tests/test_ugrid_dataset.py, xugrid/ugrid/conventions.py
@JoerivanEngelen: maybe this should also be replaced in [tests/test_ugrid_dataset.py](https://github.com/Deltares/xugrid/blob/d0b9459ed05b51e94a847fb44fe5efcaabb4f41d/tests/test_ugrid_dataset.py#L1136) (and one additional line)
=> replace .dims with .sizes

docs/changelog.rst, tests/test_partitioning.py, xugrid/ugrid/partitioning.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py, xugrid/ugrid/ugridbase.py
Fix #134 and #86,
Add support for merging partitions with different grids in each partition, for example 1D grid in one partition and 2D grids in each. Quite some refactoring was required:
* groups grids, data_objects, and other_vars by gridname
* all partitions with a certain grid should have the same variables, this is validated
* connectivity dims are padded to maximum size if not consistent
* add property to AbstractUgrid to get connectivity dimension names
=> Issue #134 merge partitions with inconsistent grids amongst partitions

docs/changelog.rst, tests/test_regrid/test_reduce.py, tests/test_regrid/test_regridder.py, xugrid/regrid/reduce.py
Fixes #236 
There was some erroneous indexing going on in ``regrid.reduce.mode`` method: the provided indexes were being ignored in some places and instead indexes starting from 0 were generated. This resulted in the method having a tendency to repeat the first value across the target grid. I also added some tests which show the bug being fixed.
Working on updating the changelog.
=> Issue #236 fix indexing in mode method regridding

xugrid/data/sample_data.py
Use of path as a context manager is deprecated and leads to a warning. In this case, just assigning the variable directly, solves the problem.
=> fix path deprecation warning

docs/changelog.rst, tests/test_partitioning.py, xugrid/ugrid/partitioning.py
This addresses #252
Also related to: https://github.com/Deltares/dfm_tools/issues/679
=> Merge partition chunks

docs/api.rst, docs/changelog.rst, pixi.lock, pyproject.toml, tests/test_ugrid1d.py, tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/core/accessorbase.py, xugrid/core/wrap.py, xugrid/ugrid/burn.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py, xugrid/ugrid/ugridbase.py
Fixes https://github.com/Deltares/xugrid/issues/265
Facet keyword works nicer with shared logic and inheritance than explicit methods.
=> From data constructors for UgridDataArray

docs/changelog.rst, examples/overlap_regridder.py, tests/test_regrid/test_reduce.py, tests/test_regrid/test_regridder.py, xugrid/regrid/nanpercentile.py, xugrid/regrid/reduce.py, xugrid/regrid/regridder.py
* Simplify methods by just giving a contiguous values array instead of source and indices
* Provide a pre-allocated workspace to avoid dynamic allocation in reduce functions
* Add a generalized percentile function
Fixes #240
=> Refactor reduce module; improve performance for mode, median

docs/changelog.rst, tests/test_ugrid1d.py, tests/test_ugrid2d.py, xugrid/core/accessorbase.py, xugrid/core/dataarray_accessor.py, xugrid/core/dataset_accessor.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py, xugrid/ugrid/ugridbase.py
Provide some options instead.
Fixes #100
Both this and the changing weights of the regridder reductions are breaking changes, the next version should be a bigger increment in version number.
=> Do not drop out-of-bounds point silently in sel_points

tests/test_core_utils.py, tests/test_ugrid1d.py, tests/test_ugrid2d.py, xugrid/ugrid/ugridbase.py
=> Let grid attrs property return a deepcopy

tests/test_partitioning.py, xugrid/ugrid/partitioning.py
=> caught empty list of partitions in xu.merge_partitions()

docs/changelog.rst, examples-dev/voronoi.py, tests/test_connectivity.py, tests/test_conversion.py, tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, tests/test_voronoi.py, xugrid/constants.py, xugrid/conversion.py, xugrid/plot/plot.py, xugrid/regrid/unstructured.py, xugrid/ugrid/connectivity.py, xugrid/ugrid/partitioning.py, xugrid/ugrid/polygonize.py, xugrid/ugrid/snapping.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py, xugrid/ugrid/ugridbase.py, xugrid/ugrid/voronoi.py
The external fill value is only used when converting back to dataset.
Fixes #298
(Should've done this long ago, there was more than one place where a fill value != -1 might have resulted in an error.)
The error of #298 makes the last release unfortunately quite broken for datasets where a fill_value != -1 was used.
@veenstrajelmer, you might want to run the dfm tools tests with this as well. The fill values were used in a lot of places, it's possible the xugrid test still have some soft spots. If there are any failures, we should patch them and add them as new tests.
=> Use a FILL_VALUE=-1 everywhere

docs/api.rst, docs/changelog.rst, tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/core/wrap.py, xugrid/ugrid/ugrid2d.py
=> From structured dataset

tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/ugrid/connectivity.py
Define cross2d instead of deprecated numpy.cross. Make dims test robust for future xarray changes. Fixes #312
=> cross2d, xarray dataset dims

docs/api.rst, docs/changelog.rst, tests/fixtures/fixture_regridder.py, tests/test_conversion.py, tests/test_regrid/test_regridder.py, tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/conversion.py, xugrid/core/wrap.py, xugrid/ugrid/interpolate.py, xugrid/ugrid/ugrid2d.py
=> From structured curvilinear

tests/test_ugrid_dataset.py, xugrid/core/wrap.py
X and Y coords aren't relevant; they're stored in the Ugrid topology.
In particular, the original bounds might be somewhat messy (e.g. the triangle stuff...). If user want the coordinates, they can use https://deltares.github.io/xugrid/api/xugrid.UgridDatasetAccessor.assign_face_coords.html
Which are nice and consistent (i.e. counterclockwise, and without repeated vertices).
=> Omit x, y coordinates, x & y bounds from conversion

tests/test_ugrid_dataset.py, xugrid/ugrid/interpolate.py
Fix issue #353
Fix ZeroDivisionError, added a unittest for it. Also I noticed that for some reason the Laplace Interpolate would do the following thing:
```[1.0, np.nan, 1.0] -> [np.nan, np.nan, np.nan]```
Hence why I resorted to interpolating from 1 to 0 in the unittest. Will be picked up upon in a follow-up issue.
=> Issue #353 ilu preconditioner zero division error

docs/changelog.rst, pixi.lock, pyproject.toml, tests/test_burn.py, tests/test_regrid/test_structured.py, tests/test_ugrid1d.py, tests/test_ugrid2d.py, xugrid/regrid/regridder.py, xugrid/regrid/structured.py, xugrid/regrid/unstructured.py, xugrid/ugrid/burn.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py, xugrid/ugrid/ugridbase.py
Add tolerance argument, to allow configuring the tolerated distance to edges in numba_celltree. I also applied the changes made in numba_celltree (evaluate distance less than tolerance instead of area) to functions in the ``burn_geometry`` functions. 
For now depend on numba_celltree 0.4.1 on PyPI in the dev build until it is released on conda-forge. I'll change that back before merging this to main.
=> Add tolerance argument

.github/workflows/ci.yml, docs/api.rst, docs/changelog.rst, pixi.lock, pyproject.toml, tests/test_ugrid1d.py, tests/test_ugrid2d.py, tests/test_ugrid_dataset.py, xugrid/core/dataarray_accessor.py, xugrid/ugrid/ugrid1d.py, xugrid/ugrid/ugrid2d.py
Closes #173
Turns out this is very easy! If we set the target dimension in the indexer, the result will have a ugrid dim, and so it'll work nicely. Then, any reduction can be applied along the new axis.
The only thing I'm not sure about is the name of the new dimension. This cannot be the name of the old dimension, because that will create an alignment issue. In this case, it'll be the aspect name (so e.g. node, edge, face) but that might already exist.
I'd like the name to be predictable, so a user can directly apply it in a reduction. Maybe the simplest idea is to require an additional argument?
=> to_facet method
